# Generated by Django 3.2 on 2021-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210724_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.RemoveField(
            model_name='task',
            name='language',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
