# Generated by Django 3.2 on 2021-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210724_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('EUR', 'Euro'), ('GBP', 'Pound')], default='Indian Rupee', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='language',
            field=models.CharField(blank=True, choices=[('ENG', 'English'), ('SPA', 'Spanish'), ('CHI', 'Chinese'), ('FRA', 'French'), ('GER', 'German'), ('HIN', 'Hindi'), ('JPN', 'Japanese'), ('AR', 'Arabic')], default='English', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
