# Generated by Django 3.2 on 2021-07-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210724_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicearea',
            old_name='poly',
            new_name='coordinates',
        ),
    ]
